import json
import io
import streamlit as st
from PIL import Image

from agents.agent1_source_retrieval import retrieve
from agents.agent2_content_generator import run_agent2
from output.creative_storyteller import generate_output

# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------

st.set_page_config(
    page_title="NYC International Student AI Influencer",
    page_icon="🗽",
    layout="wide",
)

# ---------------------------------------------------------------------------
# Sidebar — architecture overview
# ---------------------------------------------------------------------------

with st.sidebar:
    st.title("Pipeline")
    st.markdown("""
**Agent 1 — Source Retrieval**
- NYC Open Data (311, Jobs, CUNY)
- RSS feeds (NYT Education, Immigration)
- Gemini embeddings + vector search

↓

**Agent 2 — Trend Generator**
- Trend detection via Gemini Flash
- Content generation (Google ADK)
- QC self-review loop

↓

**Creative Storyteller**
- Imagen 3 image generation
- Gemini interleaved output
- Platform formatting
    """)
    st.divider()
    st.caption("Powered by Google ADK + Gemini 2.0 Flash + Imagen 3")
    st.caption("NYC Build With AI Hackathon 2026")

# ---------------------------------------------------------------------------
# Main UI
# ---------------------------------------------------------------------------

st.title("NYC International Student AI Influencer")
st.subheader("Surfacing civic inequities for international students in NYC")

TOPICS = [
    "Housing costs for international students in NYC",
    "Visa work restrictions (OPT/CPT)",
    "CUNY enrollment trends for international students",
    "Best neighborhoods for international students",
    "NYC job market for international graduates",
]

topic = st.selectbox("Select a topic to generate a post about:", TOPICS)
platform = st.radio("Platform", ["linkedin", "instagram"], horizontal=True)

generate_btn = st.button("Generate Post", type="primary", use_container_width=True)

# ---------------------------------------------------------------------------
# Pipeline execution
# ---------------------------------------------------------------------------

if generate_btn:
    st.divider()

    retrieval_pack = None
    content_draft = None
    final_output = None

    with st.status("Running pipeline...", expanded=True) as status:
        st.write("Retrieving NYC Open Data and articles...")
        try:
            retrieval_pack = retrieve(topic)
            st.write(f"Retrieved {len(retrieval_pack['results'])} relevant sources")
        except Exception as e:
            st.error(f"Agent 1 failed: {e}")
            st.stop()

        st.write("Detecting trend and generating content...")
        try:
            content_draft = run_agent2(retrieval_pack)
            content_draft["platform"] = platform
            st.write(f"Trend: {content_draft.get('topic', '')}")
        except Exception as e:
            st.error(f"Agent 2 failed: {e}")
            st.stop()

        st.write("Generating image and finalizing post...")
        try:
            final_output = generate_output(content_draft)
        except Exception as e:
            st.error(f"Creative Storyteller failed: {e}")
            st.stop()

        status.update(label="Post generated!", state="complete")

    # -----------------------------------------------------------------------
    # Output display
    # -----------------------------------------------------------------------

    urgency_color = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(
        final_output.get("urgency", "medium"), "🟡"
    )
    st.markdown(f"### {urgency_color} {content_draft.get('topic', topic)}")

    col1, col2 = st.columns([1, 1])

    with col1:
        image_bytes = final_output.get("image_bytes")
        if image_bytes:
            image = Image.open(io.BytesIO(image_bytes))
            st.image(image, caption="Generated by Imagen 3", use_container_width=True)
        else:
            st.info("Image generation unavailable — Vertex AI credentials needed.")

    with col2:
        body = final_output.get("body") or final_output.get("caption", "")
        st.markdown(body)
        st.markdown(f"**{final_output.get('hashtags', '')}**")

    # Sources
    with st.expander("NYC Data Sources Used"):
        for url in final_output.get("sources", []):
            st.markdown(f"- {url}")

    # Raw JSON for judges / debugging
    with st.expander("Raw pipeline output (for judges)"):
        st.json({
            "retrieval_pack_summary": {
                "query_topic": retrieval_pack["query_topic"],
                "results_count": len(retrieval_pack["results"]),
                "top_result": retrieval_pack["results"][0] if retrieval_pack["results"] else {},
            },
            "content_draft": content_draft,
        })
